// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByF8xCCt4nZiMmAPJ2lahIwqRDwOW-vgY',
    appId: '1:317147165424:web:acf8308c8ac392bb9bc835',
    messagingSenderId: '317147165424',
    projectId: 'formation-lh-23',
    authDomain: 'formation-lh-23.firebaseapp.com',
    storageBucket: 'formation-lh-23.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNDnQsTOUz5Nd-RxpcRSdvSvh4OE8A2sc',
    appId: '1:317147165424:android:3a96ecc366e6eb419bc835',
    messagingSenderId: '317147165424',
    projectId: 'formation-lh-23',
    storageBucket: 'formation-lh-23.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCr9tac0vembkcfDQc90edwdD4HRUudCuU',
    appId: '1:317147165424:ios:8e66924586beafd29bc835',
    messagingSenderId: '317147165424',
    projectId: 'formation-lh-23',
    storageBucket: 'formation-lh-23.appspot.com',
    iosBundleId: 'com.example.formationLh23',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCr9tac0vembkcfDQc90edwdD4HRUudCuU',
    appId: '1:317147165424:ios:a7e0719b1878ee709bc835',
    messagingSenderId: '317147165424',
    projectId: 'formation-lh-23',
    storageBucket: 'formation-lh-23.appspot.com',
    iosBundleId: 'com.example.formationLh23.RunnerTests',
  );
}
